apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-curator-cm
data:
  elasticsearch_host: '35.223.189.138'
  elasticsearch_port: '9200'
  pattern: '^(metric|heart|file)beat-.*'
  unit_count:  '13'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-curator-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      service: elasticsearch-curator
  template:
    metadata:
      labels:
        app: elasticsearch-curator
        service: elasticsearch-curator  #labels for the pods e.g kubectl get pod -l "service in (http-server)"
        version: 0.0.1
    spec:
      containers:
      - name: elasticsearch-curator
        image: docker.io/hardeep527/curator:1.6 #private Docker registry
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: my-http
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        env:
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-curator-cm 
              key: elasticsearch_host
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-curator-cm
              key: elasticsearch_port

        - name: PATTERN
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-curator-cm
              key: pattern
        - name: UNITCOUNT
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-curator-cm
              key: unit_count
